package firsttestngPackage;

import org.apache.commons.mail.Email;

//Generated by Selenium IDE


import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;


import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;


import java.util.List;

public class RegisterTest {
private WebDriver driver;

String driverPath = "C:\\Users\\gbalaji\\Desktop\\MyFiles\\Demo_Documents\\SeleniumJars\\geckodriver-v0.31.0-win64\\geckodriver.exe";

@BeforeTest
public void setUp() {
	
	System.out.println("launching firefox browser"); 
    
    //Browser initialization
    
    System.setProperty("webdriver.gecko.driver", driverPath);
    
    driver = new FirefoxDriver();
 
}

@AfterTest
public void tearDown() {
 driver.quit();
 
 //Email.reportByEmail("target/surefire-reports/emailable-report.html");
}

@Test
public void register1() {
	

 System.out.println("Launching application url");
 
 driver.get("https://demo.guru99.com/test/newtours/");
 
 driver.manage().window().setSize(new Dimension(1058, 670));
 
 System.out.println("Clicking on Register link to register new information");

 driver.findElement(By.linkText("REGISTER")).click();
 
 System.out.println("Sending user data");
 
 driver.findElement(By.name("firstName")).click();
 driver.findElement(By.name("firstName")).sendKeys("SWETHA");
 driver.findElement(By.name("lastName")).sendKeys("B");
 driver.findElement(By.name("phone")).sendKeys("7874543");
 driver.findElement(By.id("userName")).sendKeys("ksjhfSDF@test.com");
 driver.findElement(By.name("address1")).sendKeys("Car STreet");
 driver.findElement(By.name("city")).sendKeys("Chennai");
 driver.findElement(By.name("state")).sendKeys("TamilNadu");
 driver.findElement(By.name("postalCode")).sendKeys("384676");
 
 {
   WebElement dropdown = driver.findElement(By.name("country"));
   dropdown.findElement(By.xpath("//option[. = 'INDIA']")).click();
 }
 driver.findElement(By.id("email")).sendKeys("swethatest");
 driver.findElement(By.name("password")).sendKeys("admin123");
 driver.findElement(By.name("confirmPassword")).sendKeys("admin123");
 driver.findElement(By.name("submit")).click();

 System.out.println("Verify user registered or not");
 
 {
   List<WebElement> elements = driver.findElements(By.linkText("sign-in"));
   assert(elements.size() > 0);
 }
 driver.close();
}
}
